apiVersion: v1
kind: Service
metadata:
  name: serverNpservice-srv
spec:
  type: NodePort
  selector:
    app: serverservice #To know where to reach out
  ports:
    - name: serverservice
      protocol: TCP
      port: 80
      targetPort: 80